//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkEnergy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialogue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogue() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkEnergy.Resources.Dialogue", typeof(Dialogue).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awaken, {N}.\n\nYou have been freed from death&apos;s grip.\n\nYour body has been torn asunder,\nbut the Dark Energy that courses through your veins has brought you back to life ....
        /// </summary>
        internal static string Acolyte1_Body1 {
            get {
                return ResourceManager.GetString("Acolyte1_Body1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... You are too weak to speak.\n\nGather your strength and wait. I will return to you once I finish my work.\n\nFor now, you are not the only one..
        /// </summary>
        internal static string Acolyte1_Body2 {
            get {
                return ResourceManager.GetString("Acolyte1_Body2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [You are unable to speak].
        /// </summary>
        internal static string Acolyte1_Footer1 {
            get {
                return ResourceManager.GetString("Acolyte1_Footer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... Y-yes..
        /// </summary>
        internal static string Acolyte1_Footer2 {
            get {
                return ResourceManager.GetString("Acolyte1_Footer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Awakening.
        /// </summary>
        internal static string Acolyte1_Header {
            get {
                return ResourceManager.GetString("Acolyte1_Header", resourceCulture);
            }
        }
    }
}
