//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkEnergy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkEnergy.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string AbilityDisabled {
            get {
                return ResourceManager.GetString("AbilityDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RANK.
        /// </summary>
        public static string AbilityRank {
            get {
                return ResourceManager.GetString("AbilityRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AbilityRankCurrent {
            get {
                return ResourceManager.GetString("AbilityRankCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Upgrade).
        /// </summary>
        public static string AbilityRankNext {
            get {
                return ResourceManager.GetString("AbilityRankNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  DE.
        /// </summary>
        public static string AbilityResource {
            get {
                return ResourceManager.GetString("AbilityResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Energy.
        /// </summary>
        public static string AbilityResourceFull {
            get {
                return ResourceManager.GetString("AbilityResourceFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armor.
        /// </summary>
        public static string Attribute_Armor {
            get {
                return ResourceManager.GetString("Attribute_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intuition.
        /// </summary>
        public static string Attribute_Intuition {
            get {
                return ResourceManager.GetString("Attribute_Intuition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reflexes.
        /// </summary>
        public static string Attribute_Reflexes {
            get {
                return ResourceManager.GetString("Attribute_Reflexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strength.
        /// </summary>
        public static string Attribute_Strength {
            get {
                return ResourceManager.GetString("Attribute_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigor.
        /// </summary>
        public static string Attribute_Vigor {
            get {
                return ResourceManager.GetString("Attribute_Vigor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitality.
        /// </summary>
        public static string Attribute_Vitality {
            get {
                return ResourceManager.GetString("Attribute_Vitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon Damage.
        /// </summary>
        public static string Attribute_WeaponDamage {
            get {
                return ResourceManager.GetString("Attribute_WeaponDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have leveled up!.
        /// </summary>
        public static string BattleEndLevelUp {
            get {
                return ResourceManager.GetString("BattleEndLevelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have lost this battle..
        /// </summary>
        public static string BattleEndLost {
            get {
                return ResourceManager.GetString("BattleEndLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewards.
        /// </summary>
        public static string BattleEndRewards {
            get {
                return ResourceManager.GetString("BattleEndRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have won this battle..
        /// </summary>
        public static string BattleEndWon {
            get {
                return ResourceManager.GetString("BattleEndWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot upgrade this ability any further..
        /// </summary>
        public static string CannotUpgradeAbility {
            get {
                return ResourceManager.GetString("CannotUpgradeAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face.
        /// </summary>
        public static string Character_Face {
            get {
                return ResourceManager.GetString("Character_Face", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Character_Female {
            get {
                return ResourceManager.GetString("Character_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Character_Gender {
            get {
                return ResourceManager.GetString("Character_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hair.
        /// </summary>
        public static string Character_Hair {
            get {
                return ResourceManager.GetString("Character_Hair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Character_Male {
            get {
                return ResourceManager.GetString("Character_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string Character_Race {
            get {
                return ResourceManager.GetString("Character_Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin.
        /// </summary>
        public static string Character_Skin {
            get {
                return ResourceManager.GetString("Character_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Creation.
        /// </summary>
        public static string CharacterCreation {
            get {
                return ResourceManager.GetString("CharacterCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete.
        /// </summary>
        public static string CharacterDeletionConfirmation {
            get {
                return ResourceManager.GetString("CharacterDeletionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Selection.
        /// </summary>
        public static string CharacterList {
            get {
                return ResourceManager.GetString("CharacterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abilities.
        /// </summary>
        public static string CharacterMenu_Abilities {
            get {
                return ResourceManager.GetString("CharacterMenu_Abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string CharacterMenu_Attributes {
            get {
                return ResourceManager.GetString("CharacterMenu_Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string CharacterMenu_General {
            get {
                return ResourceManager.GetString("CharacterMenu_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must name your character..
        /// </summary>
        public static string CharacterNameAlert {
            get {
                return ResourceManager.GetString("CharacterNameAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements.
        /// </summary>
        public static string CodexMenu_Achievements {
            get {
                return ResourceManager.GetString("CodexMenu_Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quests.
        /// </summary>
        public static string CodexMenu_Quests {
            get {
                return ResourceManager.GetString("CodexMenu_Quests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to flee the battle?.
        /// </summary>
        public static string CombatExitConfirmationLine1 {
            get {
                return ResourceManager.GetString("CombatExitConfirmationLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will count as a loss..
        /// </summary>
        public static string CombatExitConfirmationLine2 {
            get {
                return ResourceManager.GetString("CombatExitConfirmationLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR.
        /// </summary>
        public static string CombatMessageAir {
            get {
                return ResourceManager.GetString("CombatMessageAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DARKNESS.
        /// </summary>
        public static string CombatMessageDarkness {
            get {
                return ResourceManager.GetString("CombatMessageDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EARTH.
        /// </summary>
        public static string CombatMessageEarth {
            get {
                return ResourceManager.GetString("CombatMessageEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EVADED.
        /// </summary>
        public static string CombatMessageEvaded {
            get {
                return ResourceManager.GetString("CombatMessageEvaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRE.
        /// </summary>
        public static string CombatMessageFire {
            get {
                return ResourceManager.GetString("CombatMessageFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEALED.
        /// </summary>
        public static string CombatMessageHealed {
            get {
                return ResourceManager.GetString("CombatMessageHealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICE.
        /// </summary>
        public static string CombatMessageIce {
            get {
                return ResourceManager.GetString("CombatMessageIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHT.
        /// </summary>
        public static string CombatMessageLight {
            get {
                return ResourceManager.GetString("CombatMessageLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSED.
        /// </summary>
        public static string CombatMessageMissed {
            get {
                return ResourceManager.GetString("CombatMessageMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHYSICAL.
        /// </summary>
        public static string CombatMessagePhysical {
            get {
                return ResourceManager.GetString("CombatMessagePhysical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RESISTED.
        /// </summary>
        public static string CombatMessageResisted {
            get {
                return ResourceManager.GetString("CombatMessageResisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOCK.
        /// </summary>
        public static string CombatMessageShock {
            get {
                return ResourceManager.GetString("CombatMessageShock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATER.
        /// </summary>
        public static string CombatMessageWater {
            get {
                return ResourceManager.GetString("CombatMessageWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Changes.
        /// </summary>
        public static string ConfirmChanges {
            get {
                return ResourceManager.GetString("ConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string CreateCharacter {
            get {
                return ResourceManager.GetString("CreateCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Currency_Coins {
            get {
                return ResourceManager.GetString("Currency_Coins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DC.
        /// </summary>
        public static string Currency_DarkCrystals {
            get {
                return ResourceManager.GetString("Currency_DarkCrystals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DeleteCharacter {
            get {
                return ResourceManager.GetString("DeleteCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Energy generation.
        /// </summary>
        public static string DescriptionDarkEnergy {
            get {
                return ResourceManager.GetString("DescriptionDarkEnergy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evasion.
        /// </summary>
        public static string DescriptionEvasion {
            get {
                return ResourceManager.GetString("DescriptionEvasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string DescriptionHealth {
            get {
                return ResourceManager.GetString("DescriptionHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magical power.
        /// </summary>
        public static string DescriptionMagicalDamage {
            get {
                return ResourceManager.GetString("DescriptionMagicalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical damage.
        /// </summary>
        public static string DescriptionPhysicalDamage {
            get {
                return ResourceManager.GetString("DescriptionPhysicalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defense.
        /// </summary>
        public static string DescriptionProtection {
            get {
                return ResourceManager.GetString("DescriptionProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {T} absorbs {V} percent of damage received..
        /// </summary>
        public static string EffectAbsorbDamagePercentage {
            get {
                return ResourceManager.GetString("EffectAbsorbDamagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {T} absorbs {V} damage..
        /// </summary>
        public static string EffectAbsorbDamageRaw {
            get {
                return ResourceManager.GetString("EffectAbsorbDamageRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {T} absorbs {V} percent of magical damage received..
        /// </summary>
        public static string EffectAbsorbMagicPercentage {
            get {
                return ResourceManager.GetString("EffectAbsorbMagicPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {T} absorbs {V} magical damage..
        /// </summary>
        public static string EffectAbsorbMagicRaw {
            get {
                return ResourceManager.GetString("EffectAbsorbMagicRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {T} absorbs {V} physical damage received..
        /// </summary>
        public static string EffectAbsorbPhysicalDamagePercentage {
            get {
                return ResourceManager.GetString("EffectAbsorbPhysicalDamagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {T} absorbs {V} percent of physical damage received..
        /// </summary>
        public static string EffectAbsorbPhysicalDamageRaw {
            get {
                return ResourceManager.GetString("EffectAbsorbPhysicalDamageRaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} air damage to the {T}..
        /// </summary>
        public static string EffectAirDamage {
            get {
                return ResourceManager.GetString("EffectAirDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} darkness damage to the {T}..
        /// </summary>
        public static string EffectDarknessDamage {
            get {
                return ResourceManager.GetString("EffectDarknessDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drains {V} life from the {T}..
        /// </summary>
        public static string EffectDrainLife {
            get {
                return ResourceManager.GetString("EffectDrainLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} earth damage to the {T}..
        /// </summary>
        public static string EffectEarthDamage {
            get {
                return ResourceManager.GetString("EffectEarthDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} fire damage to the {T}..
        /// </summary>
        public static string EffectFireDamage {
            get {
                return ResourceManager.GetString("EffectFireDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heals the {T} for {V}..
        /// </summary>
        public static string EffectHeal {
            get {
                return ResourceManager.GetString("EffectHeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} ice damage to the {T}..
        /// </summary>
        public static string EffectIceDamage {
            get {
                return ResourceManager.GetString("EffectIceDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases all damage dealt by the {T} by {V}%..
        /// </summary>
        public static string EffectIncreaseDamagePercentage {
            get {
                return ResourceManager.GetString("EffectIncreaseDamagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the {T}&apos;s magical power by {V}%..
        /// </summary>
        public static string EffectIncreaseMagicPercentage {
            get {
                return ResourceManager.GetString("EffectIncreaseMagicPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases all physical damage dealt by the {T} by {V}%..
        /// </summary>
        public static string EffectIncreasePhysicalDamagePercentage {
            get {
                return ResourceManager.GetString("EffectIncreasePhysicalDamagePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} light damage to the {T}..
        /// </summary>
        public static string EffectLightDamage {
            get {
                return ResourceManager.GetString("EffectLightDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} damage to the {T}..
        /// </summary>
        public static string EffectPhysicalDamage {
            get {
                return ResourceManager.GetString("EffectPhysicalDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resurrects the {T} and restores {V}% of its health..
        /// </summary>
        public static string EffectRevive {
            get {
                return ResourceManager.GetString("EffectRevive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} shock damage to the {T}..
        /// </summary>
        public static string EffectShockDamage {
            get {
                return ResourceManager.GetString("EffectShockDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string EffectTarget {
            get {
                return ResourceManager.GetString("EffectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted group.
        /// </summary>
        public static string EffectTargetedGroup {
            get {
                return ResourceManager.GetString("EffectTargetedGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Active for {R} rounds..
        /// </summary>
        public static string EffectUptime {
            get {
                return ResourceManager.GetString("EffectUptime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals {V} water damage to the {T}..
        /// </summary>
        public static string EffectWaterDamage {
            get {
                return ResourceManager.GetString("EffectWaterDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defensive.
        /// </summary>
        public static string ElementDefensive {
            get {
                return ResourceManager.GetString("ElementDefensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offensive.
        /// </summary>
        public static string ElementOffensive {
            get {
                return ResourceManager.GetString("ElementOffensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Open Character Slot&gt;.
        /// </summary>
        public static string EmptyCharacterSlot {
            get {
                return ResourceManager.GetString("EmptyCharacterSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Exit.
        /// </summary>
        public static string ExitMenu_Exit {
            get {
                return ResourceManager.GetString("ExitMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game.
        /// </summary>
        public static string ExitMenu_Save {
            get {
                return ResourceManager.GetString("ExitMenu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string Experience {
            get {
                return ResourceManager.GetString("Experience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You wake up in an unknown forest..
        /// </summary>
        public static string Intro_Message {
            get {
                return ResourceManager.GetString("Intro_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string InventoryFilters_All {
            get {
                return ResourceManager.GetString("InventoryFilters_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armors.
        /// </summary>
        public static string InventoryFilters_Armors {
            get {
                return ResourceManager.GetString("InventoryFilters_Armors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string InventoryFilters_Misc {
            get {
                return ResourceManager.GetString("InventoryFilters_Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapons.
        /// </summary>
        public static string InventoryFilters_Weapons {
            get {
                return ResourceManager.GetString("InventoryFilters_Weapons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes Gained.
        /// </summary>
        public static string InventoryMenu_AttributeImprovements {
            get {
                return ResourceManager.GetString("InventoryMenu_AttributeImprovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string InventoryMenu_Details {
            get {
                return ResourceManager.GetString("InventoryMenu_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string InventoryMenu_Equipment {
            get {
                return ResourceManager.GetString("InventoryMenu_Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string InventoryMenu_Inventory {
            get {
                return ResourceManager.GetString("InventoryMenu_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete an equipped item..
        /// </summary>
        public static string InventoryMenu_MessageDeleteFailure {
            get {
                return ResourceManager.GetString("InventoryMenu_MessageDeleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have deleted {I}..
        /// </summary>
        public static string InventoryMenu_MessageDeleteSuccess {
            get {
                return ResourceManager.GetString("InventoryMenu_MessageDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have equipped {I}..
        /// </summary>
        public static string InventoryMenu_MessageEquip {
            get {
                return ResourceManager.GetString("InventoryMenu_MessageEquip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot unequip this item..
        /// </summary>
        public static string InventoryMenu_MessageUnequipFailure {
            get {
                return ResourceManager.GetString("InventoryMenu_MessageUnequipFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your {S} slot item has been unequipped..
        /// </summary>
        public static string InventoryMenu_MessageUnequipSuccess {
            get {
                return ResourceManager.GetString("InventoryMenu_MessageUnequipSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have used {I}..
        /// </summary>
        public static string InventoryMenu_MessageUse {
            get {
                return ResourceManager.GetString("InventoryMenu_MessageUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string InventoryMenu_View {
            get {
                return ResourceManager.GetString("InventoryMenu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Item_Buy {
            get {
                return ResourceManager.GetString("Item_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Item_Delete {
            get {
                return ResourceManager.GetString("Item_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equip.
        /// </summary>
        public static string Item_Equip {
            get {
                return ResourceManager.GetString("Item_Equip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Equipped).
        /// </summary>
        public static string Item_Equipped {
            get {
                return ResourceManager.GetString("Item_Equipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Item_Sell {
            get {
                return ResourceManager.GetString("Item_Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unequip.
        /// </summary>
        public static string Item_Unequip {
            get {
                return ResourceManager.GetString("Item_Unequip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string Item_Use {
            get {
                return ResourceManager.GetString("Item_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Item_Value {
            get {
                return ResourceManager.GetString("Item_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ItemBack {
            get {
                return ResourceManager.GetString("ItemBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        public static string ItemChest {
            get {
                return ResourceManager.GetString("ItemChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feet.
        /// </summary>
        public static string ItemFeet {
            get {
                return ResourceManager.GetString("ItemFeet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger.
        /// </summary>
        public static string ItemFinger {
            get {
                return ResourceManager.GetString("ItemFinger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hands.
        /// </summary>
        public static string ItemHands {
            get {
                return ResourceManager.GetString("ItemHands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head.
        /// </summary>
        public static string ItemHead {
            get {
                return ResourceManager.GetString("ItemHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legs.
        /// </summary>
        public static string ItemLegs {
            get {
                return ResourceManager.GetString("ItemLegs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string ItemMisc {
            get {
                return ResourceManager.GetString("ItemMisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neck.
        /// </summary>
        public static string ItemNeck {
            get {
                return ResourceManager.GetString("ItemNeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ItemNone {
            get {
                return ResourceManager.GetString("ItemNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relic.
        /// </summary>
        public static string ItemRelic {
            get {
                return ResourceManager.GetString("ItemRelic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weapon.
        /// </summary>
        public static string ItemWeapon {
            get {
                return ResourceManager.GetString("ItemWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading battle....
        /// </summary>
        public static string LoadingBattle {
            get {
                return ResourceManager.GetString("LoadingBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading world....
        /// </summary>
        public static string LoadingWorld {
            get {
                return ResourceManager.GetString("LoadingWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        public static string MainMenu_Community {
            get {
                return ResourceManager.GetString("MainMenu_Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string MainMenu_Feedback {
            get {
                return ResourceManager.GetString("MainMenu_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Game.
        /// </summary>
        public static string MainMenu_PlayGame {
            get {
                return ResourceManager.GetString("MainMenu_PlayGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not gained any achievements..
        /// </summary>
        public static string NoAchievementsMessage {
            get {
                return ResourceManager.GetString("NoAchievementsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your quest log is empty..
        /// </summary>
        public static string NoQuestsMessage {
            get {
                return ResourceManager.GetString("NoQuestsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAY.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have $ unspent attribute points..
        /// </summary>
        public static string RemainingAttributePoints {
            get {
                return ResourceManager.GetString("RemainingAttributePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have $ unspent mastery points..
        /// </summary>
        public static string RemainingMasteryPoints {
            get {
                return ResourceManager.GetString("RemainingMasteryPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR.
        /// </summary>
        public static string ResistanceAir {
            get {
                return ResourceManager.GetString("ResistanceAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DARKNESS.
        /// </summary>
        public static string ResistanceDarkness {
            get {
                return ResourceManager.GetString("ResistanceDarkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EARTH.
        /// </summary>
        public static string ResistanceEarth {
            get {
                return ResourceManager.GetString("ResistanceEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIRE.
        /// </summary>
        public static string ResistanceFire {
            get {
                return ResourceManager.GetString("ResistanceFire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICE.
        /// </summary>
        public static string ResistanceIce {
            get {
                return ResourceManager.GetString("ResistanceIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHT.
        /// </summary>
        public static string ResistanceLight {
            get {
                return ResourceManager.GetString("ResistanceLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NONE.
        /// </summary>
        public static string ResistanceNone {
            get {
                return ResourceManager.GetString("ResistanceNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOCK.
        /// </summary>
        public static string ResistanceShock {
            get {
                return ResourceManager.GetString("ResistanceShock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WATER.
        /// </summary>
        public static string ResistanceWater {
            get {
                return ResourceManager.GetString("ResistanceWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap anywhere to continue..
        /// </summary>
        public static string TapToContinue {
            get {
                return ResourceManager.GetString("TapToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Energy.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string TradingBuy {
            get {
                return ResourceManager.GetString("TradingBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string TradingSell {
            get {
                return ResourceManager.GetString("TradingSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Ability.
        /// </summary>
        public static string UpgradeAbility {
            get {
                return ResourceManager.GetString("UpgradeAbility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
